[book]
title = "tbzl.dev"
authors = ["tomato-bazel"]
description = "the tomato-bazel Bazel registry + tooling"
language = "en"
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
additional-css = ["theme/css/custom.css"]
no-section-label = true
git-repository-url = "https://github.com/tomato-bazel"
edit-url-template = "https://github.com/tomato-bazel/docs/edit/main/{path}"
